// ACTION TYPES
export const actionTypes = {
	// GET_ETH_STATUS: 'GET_ETH_STATUS',
	ARTICLE_DELETE: 'ARTICLE_DELETE',
	ARTICLE_READ: 'ARTICLE_READ',
	ARTICLE_READ_ALL: 'ARTICLE_READ_ALL',
	ARTICLE_DELETE_ALL: 'ARTICLE_DELETE_ALL',
	ARTICLE_SET_ALL: 'ARTICLE_SET_ALL'
};
